### ISSUE TITLE
Monthly, yearly receipts - are those triggered for DE by FT like in AT?

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/faq#100]
I wonder if both receipts are triggered the same way as you did it for Austria using an ftState?

0x4154000000000010 | "monthly report due"If the latest monthly or annual report are not in the current month, the service will signal this. This status does not impact the signature conduct of the service, it is merely an indicative notification. | 1.0
-- | -- | --
0x4154000000000020 | "annual report due"Same conduct as for "monthly report due" | 1.0

or is DE done differently? What is the German requirement when these receipts must be created?

**Comment by Lorscheidt** [comment]
Also, where in the law does it say that those are required?

![image](https://user-images.githubusercontent.com/60941951/92100170-bd6ed700-eddb-11ea-85a7-155f0a47410b.png)

**Comment by MarkusEGruber** [comment]
The monthly-closing and yearly-closing are not required by law. We just recommend to do them at the end of the month instead of the daily, and at the end of the year instead of the daily.

It is not triggered in DE like it is in AT, because they are not mandatory.

**Comment by Lorscheidt** [comment]
Thanks a lot!
