### ISSUE TITLE
Is DSFinV-K export working on Mac?

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/faq#106]
We can't extract the zip files. Please advise if it's a mistake on our or your side. Cheers, Sonja

**Comment by MarkusEGruber** [comment]
Hi, are you talking about the journal Export on the middleware? That's not implemented yet, see https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-journal-ftjournaltype.html

**Comment by Lorscheidt** [comment]
Hey Markus,
no, it's actually when I hit the download button in the portal to download the zip file containing the DSFinV-K export.
