### ISSUE TITLE
The Receipt Total in the Portal gets rounded incorrectly

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/faq#114]
![image](https://user-images.githubusercontent.com/60941951/95594547-62b84300-0a4b-11eb-87c6-2010b0df02ac.png)
![image](https://user-images.githubusercontent.com/60941951/95594595-75327c80-0a4b-11eb-9f4e-4e60a1c0e15c.png)

**Comment by TSchmiedlechner** [comment]
Hi,
I quickly checked this, and you are right, this is a bug. We will fix this in one of the next sprints. Thank you very much for reporting this! We'll post an update here when it's done.

Have a nice evening,
Tom

**Comment by Solrosy** [comment]
Cool!
