### ISSUE TITLE
DSFinV-K and Belegabbruch / fail-transaction

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/faq#115]
Hi there,

Belegabbruch is a listed action typ in DSFinV-K.
When I create an implicit fail-transaction receipt I get the type "Kassenbeleg-V1" shown as TSE_TA_VORGANGSART.

How do I log a receipt cancellation correctly?

**Comment by TSchmiedlechner** [comment]
Hi, thanks for reaching out!
Indeed, the receipt type `0x444500000000000B` should generate `AVBelegabbruch`, but as the "BON_TYP" (_Vorgangstyp_), which is kind of a "subtype" of the `Kassenbeleg-V1`. The field `TSE_TA_VORGANGSART` is set to the _processType_ of the TSE.

You can find the BON_TYP in `transactions.csv`.
I quickly tried to reproduce it, and it works as expected for me

I hope this helps?
Tom

**Comment by Solrosy** [comment]
Thanks, Tom. I've passed on the files to the poscreator support so you can check. I can't find it in mine.
