### ISSUE TITLE
TSE expired

### ISSUE THREAD

**Issue by gms-kurt** [fiskaltrust/faq#121]
In the sandbox portal (for german market) the TSE (swissbit stick) we got for testing says "Ablaufdatum: 18.09.2020" 
and in the logging of the service we get 
```
fiskaltrust.Middleware.SCU.DE.Swissbit.Interop.Exceptions.SwissbitException: Certificate expired. 
```
Is it possible to increase the expiration date?

I'd like to test journal export.

**Comment by gms-kurt** [comment]
And is it possible to varify a journal export from our customer? Their stick is not expired.

**Comment by TSchmiedlechner** [comment]
Hi @gms-kurt,
sorry for the late response, seems like we somehow missed this issue. Unfortunately, when a TSE is expired, there's no way to increase the expiration date, so I think you'll need a new one. We also frequently ran into this problem ourselves..

Depending on the type of the journal, there are different ways to verify it. For a TAR journal, you could e.g. check if the file can be properly opened, and if it contains the expected logs without gaps. For DSFinV-K, a zip file is returned, so checking the content should also be possible (or verifying it e.g. with 7-zip, which has this functionality).

I hope this helps and especially that I get the second question right.

**Comment by TSchmiedlechner** [comment]
One more point regarding the second question: if you're using our NuGet client packages and REST or SOAP, there was an issue in previous versions that could lead to corrupted tar files when getting journals. The data was properly transmitted (i.e. the TAR file is "complete"), but included trailing `\0` sometimes, which breaks some files. 

Updating the client packages to 1.3.11 should resolve this issue, sorry for the inconvenience in case you are affected.
