### ISSUE TITLE
Two Swissbit Cloud-TSE on one Server

### ISSUE THREAD

**Issue by andispiss** [fiskaltrust/faq#143]
Hello @aedler-ft !

We have two cashboxes in operation at one customer (for each cashbox - 1 location).
Two Swissbit Cloud TSEs are connected here as SCU. The correct location allocation was ensured throughout the entire configuration.

During the configuration we paid attention to the allocation of the ports so that nothing blocks each other.

I was able to solve the first problem with the used WebServer port (20001) of the FCC. We changed the port to 20002 for the second service. (Via the "C:\ProgramData\fiskaltrust\service\fiskaltrust\FCC\sfcc-ftde-xxxx-xxxx\.fccdata\config\fiskal_local.properties" config file. --> _fiskal.local.port = 20002_)

But now we still get the following error:
**Failed to execute GetTseInfoAsync**

![error_GetTseInfoAsync](https://user-images.githubusercontent.com/80392542/114174335-c2c76d80-9938-11eb-861d-758236b407ca.png)

Does something else have to be taken into account in the configuration in order to operate two cashboxes on one server?

Thank you in advance for a short feedback.
Andreas Spiss

**Comment by aedler-ft** [comment]
Hi @andispiss ,
I'd suggest to first check the troubleshooting guide at Swissbit Cloud SCU documentation: https://docs.fiskaltrust.cloud/docs/product-description/germany/products-and-services/caas/features/basics/tse/swissbit-cloud#troubleshooting?

...and also make sure that the firewall is configured properly for the Swissbit Cloud TSE:
https://docs.fiskaltrust.cloud/docs/posdealers/get-started/sales/firewall-settings#bei-verwendung-der-deutschen-fiskal-tse--der-swissbit-cloud-tse

here are more detailed firewall setting if your fw configuration is really complex:
https://docs.fiskaltrust.cloud/docs/posdealers/get-started/after-sales/troubleshooting-firewall

keep me updated on how things are going!
Andreas

**Comment by cga99** [comment]
I have exact the same issue. I've already checked all firewallsettings

**Comment by aedler-ft** [comment]
Hi @cga99 , can you send your account name and the cashboxID to support-poscreator@fiskaltrust.de, then we'll have a look at your configuration, thank you!
Andreas

**Comment by andispiss** [comment]
Hello @aedler-ft ,
Hello @cga99 ,

We have also checked the configuration of the firewall. Nothing is blocked here. We often had problems with the connection to the middleware when using an outdated Microsoft VCRedist 2015 installation. We also have updated the vcr2015 installation. (The problem seems to be with the SCU used, because the connection to the middleware itself works.)

Unfortunately, all to no avail.

We have now also sent an email to support-poscreator@fiskaltrust.de with cashbox ID and customer account ID and name.

If someone has a solution for us, please post here!

Many Thanks!
Andreas Spiss

**Comment by aedler-ft** [comment]
Hi @andispiss ,
(hi @cga99 )

thank you for submitting additional information to support@fiskaltrust.de. We could see in the screenshot of the console with additional debug info the error message "Port 20001 Validation failed" "Port is already in use".

The FCC uses the default "20001" port for communication with the Middleware. When two FCC are running on the same machine, one 'FccPort' needs to be set to a different port, e.g. "20002".

You can find in the link below how to set the parameters for the 'FccPort':
https://docs.fiskaltrust.cloud/docs/product-description/germany/products-and-services/caas/features/basics/tse/swissbit-cloud#parameter

hope this could resolve the issue; please keep me updated!
thank you,
Andreas

**Comment by andispiss** [comment]
Hello @aedler-ft ,
Hello @cga99 ,

Thank you for the info.

As already mentioned in the first post, the ports have been adjusted so that they do not block each other. This was also taken into account in the second FCC.

1. Port 20002 for the second FCC was stored in the config file (in ProgramData Service folder)
2. Port 18005 for the second FCC was stored in the config in the fiscaltrust portal

In the firewall, these two ports were also excluded accordingly.

These stored ports are also used, but the exception - "Communication error (Unauthorized)" still appears (as can be seen in the screenshot)

![image](https://user-images.githubusercontent.com/80392542/116356921-2f2ce280-a7fc-11eb-9e4c-520842f02cbe.png)

SCU Config in fiscaltrust portal
![image](https://user-images.githubusercontent.com/80392542/116357002-45d33980-a7fc-11eb-8477-0592ee6f3e01.png)

Does the port to connect the FCC have to be changed elsewhere?

Here is our ticket-number: CAS-28707-N2B0Z1

Many Thanks

Andreas Spiss

**Comment by aedler-ft** [comment]
Hi @andispiss ,
can you send us the logs to the support ticket, so we can have a closer look at it?
thank you,
Andreas

**Comment by andispiss** [comment]
Hi @aedler-ft ,

Thank you - the log files have been mailed.

Andreas

**Comment by aedler-ft** [comment]
Hi @andispiss ,
thank you for the log file. According to the log file, it looks like the port has been set in the static configuration manually, What is missing, is the configuration of the FCC port in the Signature creation unit.
So in `portal/configuration/signature creation unit` you just need to edit the affected signature creation unit and set the FCC port to 20002, then rebuild the cashbox configuration and restart the launcher/service and it should be fine.

In general, just setting the FCC port in the portal should be enough so that everything is being installed and configured properly.

Just keep me updated if this resolved the problem,
Andreas

**Comment by andispiss** [comment]
Hi @aedler-ft ,

Thanks for the hint. Unfortunately, I completely overlooked this port assignment in the portal.

![image](https://user-images.githubusercontent.com/80392542/116913812-3a43a080-ac4a-11eb-9628-d3db191c7880.png)

After the correct assignment and reconfiguration of the cashbox, both services now work in parallel as desired.

Many thanks
Andreas Spiss

**Comment by aedler-ft** [comment]
@andispiss cool, thank you a  lot for the feedback, I'm glad that I could help!
Andreas
