### ISSUE TITLE
Migrate FAQ from german website to this repo

### ISSUE THREAD

**Issue by christian-rogobete** [fiskaltrust/faq#28]
Currently there are some FAQ on the german website that can be migrated to the FAQ repo. The FAQ section of the german website will soon be replaced by an auto generated section from this repo.

**Comment by christian-rogobete** [comment]
already merged a couple of FAQ with this PR: https://github.com/fiskaltrust/faq/pull/26

**Comment by aedler-ft** [comment]
done
