### ISSUE TITLE
Q: In case of fiskaltrust product/service cancelation, will the amount be reimbursed or credited? 

### ISSUE THREAD

**Issue by fiskaltrust-MBI** [fiskaltrust/faq#46]

**Comment by magdignomad** [comment]
## Metadata tags
lang-de, lang-at, market-at, portal, PosDealer, PosOperator, Consultant

## Answer
Es werden keine Gebühren vergütet. Die Zahlung aller Services erfolgt für ein Jahr im vorhinein. Die Kündigung jedes Produkts muss nachweislich rechtzeitig (entsprechend den geltenden Vertragsbedingungen) und nachweislich bei fiskaltrust erfolgen. Damit wird das Produkt mit Ende der Laufzeit nicht mehr verlängert. Eine Kündigung eines Zahlungsmandats (SEPA, slimpay, ...) oder eine nicht erfolgt Zahlung gilt nicht als Kündigung des Produktvertrags.
