### ISSUE TITLE
Q: Can a TSE be operated with more than one cash register? And if yes, what is the recommended architecture?

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/faq#57]
We got this question from a TCPOS developer. This is how we answered it, in German:

> Richtig, die Verwendung einer TSE an mehreren Kassen ist prinzipiell möglich. In dem Fall würden wir empfehlen, mehrere Cashboxen (eine pro Kassensystem) zu konfigurieren – unser Lieblingsparameter, die „Cashboxidentification“, wird auch als ClientID für die Verbindung zur TSE genutzt. Sofern diese Werte also für jede Cashbox/Signaturerstellungseinheit einzigartig sind, sollten keine Probleme auftreten.
Grundsätzlich empfehlen wir aber aus Performance-Gründen schon eher eine TSE pro Kasse, besonders im Zusammenhang mit den Exporten kann das sonst für den Benutzer sehr unangenehm werden. In jedem Fall bräuchten Sie daher für dieses Szenario einen guten Plan, wann diese lang dauernden Operationen durchgeführt werden bzw. welche Kasse sie durchführt, etc.

**Comment by aedler-ft** [comment]
#85
