### ISSUE TITLE
Beleginhalte

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/faq#65]
https://github.com/fiskaltrust/faq/blob/master/qna/DE-Rechnung-Beleg-Inhalte.md

The table is to wide and not all information is shown. If the user doesn't pay attention some important parts are not seen by them.

**Comment by aedler-ft** [comment]
unfortunately we can't influence that

**Comment by AxelKutschera** [comment]
This is the original souce: https://fiskaltrust.de/wp-content/uploads/sites/5/2019/11/20191122-ft-Belegmerkmale-DE-v0.5.pdf
