### ISSUE TITLE
Kassen-Seriennummer and CashBoxID

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/faq#83]
Hi there, 

I please need more information about what the Seriennummer which shows on the receipt must be and how we can set it.

**Comment by aedler-ft** [comment]
@MarkusEGruber this is related to https://github.com/fiskaltrust/productdescription-de-doc/tree/master/glossar#kassenseriennummer

**Comment by Lorscheidt** [comment]
KASSE_SW_BRAND Zeichen Markenbezeichnung der Software
KASSE_SW_VERSION Zeichen Version der Software

How is this transmitted please?

**Comment by TSchmiedlechner** [comment]
I hope that this was already clarified by @aedler-ft's answer - closing this now, as it's quite old. If the question is not resolved, please reach out again 🙂
